wkstn_apt_key_urls: []

wkstn_ppa: []
  # - name: shutter.... Deprecated. :-(
  #   repo: ppa:shutter/ppa

wkstn_apt_packages:
  - curl
  - tilix
  - gitk
  - gnupg-agent
  - gnupg2
  - mono-complete
  - python-pip
  - shellcheck
  - whois
  - ack
  - jq
  - ffmpeg
  #- shutter # oops .. got removed as of ubuntu 18. :-(
  - mlocate
  - net-tools

wkstn_remote_debs:
  - src: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - src: https://atom.io/download/deb
  - src: https://www.syntevo.com/downloads/smartgit/smartgit-19_1_6.deb
  - src: https://releases.mattermost.com/desktop/4.4.0/mattermost-desktop-4.4.0-linux-amd64.deb

wkstn_snap_packages:
  - name: sublime-text
    classic: true
  - name: pycharm-professional
    classic: true
  - name: slack
    classic: true
  - name: spotify
    classic: false
  - name: thunderbird
    classic: false
  - name: libreoffice
    classic: false
  - name: yq
    classic: false

wkstn_git_repos:
  - repo: 'https://github.com/magicmonty/bash-git-prompt.git'
    dest: ~/opt/bash-git-prompt

wkstn_sudo_git_repos:
  - repo: 'https://github.com/wting/autojump.git'
    dest: /usr/share/autojump

# @TODO .... configure autojump - it needs a post-download command to be run

wkstn_zips:
  - name: KeePass
    url: https://sourceforge.net/projects/keepass/files/KeePass%202.x/2.44/KeePass-2.44.zip/download
    dest: ~/opt/keepass
