---
wkstn_apt_packages:
  - curl
  - tilix
wkstn_remote_debs:
  - src: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - src: https://atom.io/download/deb
  - src: https://www.syntevo.com/downloads/smartgit/smartgit-19_1_6.deb
wkstn_snap_packages:
  - name: sublime-text
    classic: true
  - name: pycharm-professional
    classic: true
wkstn_git_repos:
  - repo: 'https://github.com/magicmonty/bash-git-prompt.git'
    dest: ~/opt/bash-git-prompt
